name: Python application

on:
  push:
    paths:
    - 'python/*'
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./python/requirements.txt
    - name: Build & Push Image
      run: |
        cd ./python
        echo "${{ secrets.DOCKERPW }}" | docker login -u "mohannademhemed" --password-stdin
        docker build -t mohannademhemed/gitops:hellov1.2 .
        docker push mohannademhemed/gitops:hellov1.2
